model_tab <- argonTabItem(
  tabName = "model",
  argonH1(display = 3, "Spatial Cross Section Models"),
  width = 12,
  argonCard(
    width = 12,
    src = NULL,
    icon = icon("cogs"),
    status = "success",
    shadow = TRUE,
    border_level = 2,
    hover_shadow = TRUE,
    title = "Model specification",
    fluidRow(
      column(
        width = 6,
        uiOutput("model_dependent_variable_UI")
      ),
      column(
        width = 6,
        uiOutput("model_independent_variable_UI")
      )
    )
  ),
  argonTabSet(
    id = "models-tab",
    card_wrapper = TRUE,
    horizontal = TRUE,
    circle = FALSE,
    size = "lg",
    width = 12,
    argonTab(
      tabName = "OLS",
      active = TRUE,
      h3("OLS model"),
      p("Ordinary Least Squares estimator for linear regression."),
      withMathJax("$$ y = X\\beta + \\varepsilon $$"),
      actionButton("model_estimate_ols", "Estimate", icon = icon("math"), status = "primary"),
      hr(),
      h4("Estimation"),
      verbatimTextOutput("model_ols_summary"),
      hr(),
      h4("Moran's I for error term"),
      verbatimTextOutput("model_ols_error"),
      hr(),
      h4("Residual map"),
      leafletOutput("model_ols_map", height = 600),
      hr(),
      h4("Lagrange multiplier"),
      verbatimTextOutput("model_ols_lagrange"),
      hr(),
      textAreaInput(inputId = "model_ols_general_observations", label = "General observations for PDF report"),
      downloadButton("model_ols_download", "Generate report")
    ),
    argonTab(
      tabName = "SAR (ML)",
      active = FALSE,
      h3("SAR (ML)"),
      p("Spatial Autoregressive (SAR) model with maximum likelihood (ML) estimator."),
      withMathJax("$$ y = \\rho Wy + X \\beta + \\varepsilon $$"),
      actionButton("model_estimate_sar_ml", "Estimate", icon = icon("math"), status = "primary"),
      hr(),
      h4("Estimation"),
      verbatimTextOutput("model_sar_ml_summary"),
      hr(),
      h4("Impacts"),
      verbatimTextOutput("model_sar_ml_impacts"),
      hr(),
      h4("Residual map"),
      leafletOutput("model_sar_ml_map", height = 600),
      hr(),
      textAreaInput(inputId = "model_sar_ml_general_observations", label = "General observations for PDF report"),
      downloadButton("model_sar_ml_download", "Generate report")
    ),
    argonTab(
      tabName = "SAR (STSLS)",
      active = FALSE,
      h3("SAR (STSLS)"),
      p("Spatial Autoregressive (SAR) model with Generalized Spatial Two Stage Least Squares (STSLS) estimator."),
      withMathJax("$$ y = \\rho Wy + X \\beta + \\varepsilon $$"),
      checkboxGroupInput("model_sar_stsls_options", "Options", choices = c("Heteroskedasticity correction" = "is_robust", "Do not use W2X as instrument" = "not_w2x")),
      actionButton("model_estimate_sar_stsls", "Estimate", icon = icon("math"), status = "primary"),
      hr(),
      h4("Estimation"),
      verbatimTextOutput("model_sar_stsls_summary"),
      hr(),
      h4("Impacts"),
      verbatimTextOutput("model_sar_stsls_impacts"),
      hr(),
      h4("Residual map"),
      leafletOutput("model_sar_stsls_map", height = 600),
      hr(),
      textAreaInput(inputId = "model_sar_stsls_general_observations", label = "General observations for PDF report"),
      downloadButton("model_sar_stsls_download", "Generate report")
    ),
    argonTab(
      tabName = "SEM (ML)",
      active = FALSE,
      h3("SEM (ML)"),
      p("Spatial Error Model (SEM) with maximum likelihood (ML) estimator."),
      withMathJax("$$ y = X \\beta + \\xi $$"),
      withMathJax("$$ \\xi = \\lambda W \\xi + \\varepsilon$$"),
      actionButton("model_estimate_sem_ml", "Estimate", icon = icon("math"), status = "primary"),
      hr(),
      h4("Estimation"),
      verbatimTextOutput("model_sem_ml_summary"),
      hr(),
      h4("Residual map"),
      leafletOutput("model_sem_ml_map", height = 600),
      hr(),
      textAreaInput(inputId = "model_sem_ml_general_observations", label = "General observations for PDF report"),
      downloadButton("model_sem_ml_download", "Generate report")
    ),
    argonTab(
      tabName = "SEM (GMM)",
      active = FALSE,
      h3("SEM (GMM)"),
      p("Spatial Error Model (SEM) with Generalized Method of Moments (GMM) estimator."),
      withMathJax("$$ y = X \\beta + \\xi $$"),
      withMathJax("$$ \\xi = \\lambda W \\xi + \\varepsilon$$"),
      actionButton("model_estimate_sem_gmm", "Estimate", icon = icon("math"), status = "primary"),
      hr(),
      h4("Estimation"),
      verbatimTextOutput("model_sem_gmm_summary"),
      hr(),
      h4("Residual map"),
      leafletOutput("model_sem_gmm_map", height = 600),
      hr(),
      textAreaInput(inputId = "model_sem_gmm_general_observations", label = "General observations for PDF report"),
      downloadButton("model_sem_gmm_download", "Generate report")
    ),
    argonTab(
      tabName = "SAC (ML)",
      active = FALSE,
      h3("SAC (ML)"),
      p("Spatial Autocorrelation Model (SAC) with maximum likelihood (ML) estimator."),
      withMathJax("$$ y = \\rho Wy + X \\beta + \\xi $$"),
      withMathJax("$$ \\xi = \\lambda W \\xi + \\varepsilon $$"),
      checkboxGroupInput("model_estimate_sac_ml_options", "Options", choices = c("Use secondary weights matrix for error term" = "use_secondary_w_matrix")),
      actionButton("model_estimate_sac_ml", "Estimate", icon = icon("math"), status = "primary"),
      hr(),
      h4("Estimation"),
      verbatimTextOutput("model_sac_ml_summary"),
      hr(),
      h4("Impacts"),
      verbatimTextOutput("model_sac_ml_impacts"),
      hr(),
      h4("Residual map"),
      leafletOutput("model_sac_ml_map", height = 600),
      hr(),
      textAreaInput(inputId = "model_sac_ml_general_observations", label = "General observations for PDF report"),
      downloadButton("model_sac_ml_download", "Generate report")
    ),
    argonTab(
      tabName = "SAC (GSTSLS)",
      active = FALSE,
      h3("SAC (GSTSLS)"),
      p("Spatial Autocorrelation Model (SAC) with Generalized Spatial Two Stage Least Squares (GSTSLS) estimator."),
      withMathJax("$$ y = \\rho Wy + X \\beta + \\xi $$"),
      withMathJax("$$ \\xi = \\lambda W \\xi + \\varepsilon $$"),
      checkboxGroupInput("model_sac_gstsls_options", "Options", choices = c("Heteroskedasticity correction" = "is_robust", "Do not use W2X as instrument" = "not_w2x", "Use secondary weights matrix for error term" = "use_secondary_w_matrix")),
      actionButton("model_estimate_sac_gstsls", "Estimate", icon = icon("math"), status = "primary"),
      hr(),
      h4("Estimation"),
      verbatimTextOutput("model_sac_gstsls_summary"),
      hr(),
      h4("Impacts"),
      verbatimTextOutput("model_sac_gstsls_impacts"),
      hr(),
      h4("Residual map"),
      leafletOutput("model_sac_gstsls_map", height = 600),
      hr(),
      textAreaInput(inputId = "model_sac_gstsls_general_observations", label = "General observations for PDF report"),
      downloadButton("model_sac_gstsls_download", "Generate report")
    ),
    argonTab(
      tabName = "SLX (ML)",
      active = FALSE,
      h3("SLX (ML)"),
      p("Spatial Lag X (SLX) model with maximum likelihood (ML) estimator."),
      withMathJax("$$ y = X \\beta + WX \\theta + \\varepsilon $$"),
      actionButton("model_estimate_slx_ml", "Estimate", icon = icon("math"), status = "primary"),
      hr(),
      h4("Estimation"),
      verbatimTextOutput("model_slx_ml_summary"),
      hr(),
      h4("Impacts"),
      verbatimTextOutput("model_slx_ml_impacts"),
      hr(),
      h4("Residual map"),
      leafletOutput("model_slx_ml_map", height = 600),
      hr(),
      textAreaInput(inputId = "model_slx_ml_general_observations", label = "General observations for PDF report"),
      downloadButton("model_slx_ml_download", "Generate report")
    ),
    argonTab(
      tabName = "SDM (ML)",
      active = FALSE,
      h3("SDM (ML)"),
      p("Spatial Durbin Model (SDM) with maximum likelihood (ML) estimator."),
      withMathJax("$$ y = \\rho Wy X \\beta + WX \\theta + \\varepsilon $$"),
      actionButton("model_estimate_sdm_ml", "Estimate", icon = icon("math"), status = "primary"),
      hr(),
      h4("Estimation"),
      verbatimTextOutput("model_sdm_ml_summary"),
      hr(),
      h4("Impacts"),
      verbatimTextOutput("model_sdm_ml_impacts"),
      hr(),
      h4("Residual map"),
      leafletOutput("model_sdm_ml_map", height = 600),
      hr(),
      textAreaInput(inputId = "model_sdm_ml_general_observations", label = "General observations for PDF report"),
      downloadButton("model_sdm_ml_download", "Generate report")
    ),
    argonTab(
      tabName = "SDEM (ML)",
      active = FALSE,
      h3("SDEM (ML)"),
      p("Spatial Durbin Error Model (SDEM) with maximum likelihood (ML) estimator."),
      withMathJax("$$ y = X \\beta + WX \\theta + \\xi $$"),
      withMathJax("$$ \\xi = \\lambda W \\xi + \\varepsilon$$"),
      actionButton("model_estimate_sdem_ml", "Estimate", icon = icon("math"), status = "primary"),
      hr(),
      h4("Estimation"),
      verbatimTextOutput("model_sdem_ml_summary"),
      hr(),
      h4("Impacts"),
      verbatimTextOutput("model_sdem_ml_impacts"),
      hr(),
      h4("Residual map"),
      leafletOutput("model_sdem_ml_map", height = 600),
      hr(),
      textAreaInput(inputId = "model_sdem_ml_general_observations", label = "General observations for PDF report"),
      downloadButton("model_sdem_ml_download", "Generate report")
    )
  )
)